[project]
name = "diffattack-v1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.*"
dependencies = [
    "accelerate",
    "adversarial-robustness-toolbox==1.13.1",
    "diffusers==0.30.3",
    "eagerpy==0.30.0",
    "ipywidgets",
    "natsort==8.2.0",
    "numpy==1.26.4",
    "opencv-python",
    "pillow==9.2.0",
    "pretrainedmodels==0.7.4",
    "scipy",
    "timm==0.4.12",
    "torch>=2.8.0",
    "torchattacks>=3.5.1",
    "torchvision",
    "tqdm==4.62.2",
    "transformers",
    "wandb",
]
